version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qweasdqwe
      - POSTGRES_DB=inlaze_db